---
title: "Chap_Intro"
output: pdf_document
date: "2025-07-07"
---

PRESENTATION DES DONNEES

## Données de communes de la Haute-Garonne

```{r}
library(sampling)
data(rec99)
dim(rec99)
#[1] 554 7
names(rec99)
#[1] "CODE_N" "COMMUNE" "BVQ_N"
#"POPSDC99" "LOG" "LOGVAC" "STRATLOG" "surf_m2" "lat_centre"
#[10] "lon_centre" "NAME_3"
```

```{r}
 sum(rec99$LOGVAC)
#[1] 10768
var(rec99$LOGVAC)
#[1] 1104.5
```

## Données de type enquête Emploi française

```{r}
TUR <- c(rep(1,2070),rep(2,1193),rep(3,1359),rep(4,1342),
rep(5,1140))
AGRI <- c(rep(0,1828),rep(1,242),rep(0,1157),rep(1,36),
 rep(0,1343),rep(1,16),rep(0,1337),rep(1,5),rep(0,1140))
EDSANTSOC <- c(rep(0,1468),rep(1,360),rep(0,1198),rep(1,201),
 rep(0,1076),rep(1,303),rep(0,1051),
 rep(1,302),rep(0,987),rep(1,158))
emploi <- data.frame(TUR,AGRI,EDSANTSOC)
dim(emploi)
#[1] 7104 3
```

```{r}
PAGRI <- mean(emploi$AGRI)
#[1] 0.04208896
var(emploi$AGRI)
#[1] 0.04032316
PEDSANTSOC <- mean(emploi$EDSANTSOC)
#[1] 0.1863739
var(emploi$EDSANTSOC)
#[1] 0.15166
```

## Données de municipalités suisses

```{r}
library(sampling)
data(swissmunicipalities)
dim(swissmunicipalities)
#[1] 2896 22
```

```{r}
sum(swissmunicipalities$Surfacesbois)
#[1] 1270996
var(swissmunicipalities$Surfacesbois)
#[1] 378682.4
```
