---
title: "chap_simples_comparaison"
output: pdf_document
date: "2025-07-09"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##  Étude de la stratégie (SI, HT) par simulations de Monte-Carlo


```{r}
require("tidyverse")###pour ggplot
require(gridExtra)##pour combiner des graphiques
library(sampling)
data(rec99)
```

```{r}
 N <- nrow(rec99)
 n <- 70
 n.sim <- 10000
```

```{r}
est.si <- numeric(n.sim)
piks <- rep(n/N,n)
set.seed(123456)
for (i in 1:n.sim)
  {
  si.rec <- srswor(n,N)
  ys <- rec99$LOGVAC[si.rec==1]
  est.si[i] <- HTestimator(ys,piks)
  }
```

```{r}
mean(est.si)
# [1] 10757.02
(cv.si <- sd(est.si)/mean(est.si))
# [1] 0.1918109
```

```{r}
ty <- sum(rec99$LOGVAC)
(mean(est.si)-ty)/ty
# [1]-0.001020021
```

## histogramme  des 10000 simulations
```{r}
est.si <- data.frame(est.si)
colnames(est.si)=c("LOGVAC")

p1 <- ggplot(est.si,aes(x=LOGVAC))+
  geom_histogram(binwidth=500)+
  geom_vline(xintercept=10768)
  #ggtitle("10000 estimations par l'estimateur HT, plan SI")

######biais de l'estimateur HT
nb.simul<-matrix(1:10000,10000,1)
est.si.cumul <- cumsum(est.si$LOGVAC)/nb.simul
df.si <- data.frame(nb.simul, est.si.cumul)
#View(df.si)

ytot <- sum(rec99$LOGVAC)
p2 <- ggplot(df.si,aes(x=nb.simul,y=est.si.cumul))+
  geom_line()+
  geom_hline(yintercept=ytot)+
  xlab("Nombre simulations")+
  ylab("Moyenne des estimations")

###mettre les deux graphiques ensemble
grid.arrange(p1,p2,nrow=1)
```

## Étude de la stratégie (BE, HT) par simulations de Monte-Carlo

```{r}
 BE1 <- function(N,Pi)
 {
 u <- runif(N, 0, 1)
 as.numeric(u<Pi)
 }
```
 
```{r}
est.be <- numeric(n.sim)
n.be <- numeric(n.sim)
set.seed(123456)
for (i in 1:n.sim)
 {
 s.be <- BE1(N,n/N)
 n.be[i] <- sum(s.be==1)
 rec.be <- rec99[s.be==1,]
 est.be[i] <- (N/n)*sum(rec.be$LOGVAC)
  }
mean(est.be)
# [1] 10764.34
(cv.be <- sd(est.be)/mean(est.be))
# [1] 0.2193195
(mean(est.be)-ty)/ty
# [1]-0.000339896
```

```{r}
quantile(n.be,probs=c(0.025,0.1,0.5,0.9,0.95,0.975))
# 2.5%  50%  55  60  90%  95% 97.5%  70  80  83  85
```

##  Étude de la stratégie (SY, HT) par simulations de Monte-Carlo

```{r}
pik <- rep(n/N,N)
est.sy <- numeric(n.sim)
set.seed(123456)
 for (i in 1:n.sim)
 {
 sy.rec <- UPsystematic(pik)
 ys <- rec99$LOGVAC[sy.rec==1]
 piks <- pik[sy.rec==1]
 est.sy[i] <- HTestimator(ys,piks)
 }
mean(est.sy)
# [1] 10774.91
(cv.sy <- sd(est.sy)/mean(est.sy))
# [1] 0.1812545
(mean(est.sy)-ty)/ty
# [1] 0.0006417162
```

```{r}
orderlog <- order(rec99$LOG)
rec.tri <- rec99[orderlog,]
```
